const std = @import("std");
const Loc = @import("../file/Loc.zig");

tag: Tag,
loc: Loc,

pub const Tag = enum(u8) {
    invalid = 0,
    eof,
    ident,
    number,
    template_args_start,
    template_args_end,
    string_literal,
    @"(",
    @")",
    @"{",
    @"}",
    @"[",
    @"]",
    @".",
    @",",
    @":",
    @";",
    @"->",
    @"@",
    @"=",
    @"==",
    @"!",
    @"!=",
    @"&",
    @"&=",
    @"&&",
    @"|",
    @"|=",
    @"||",
    @"~",
    @"+",
    @"+=",
    @"++",
    @"-",
    @"-=",
    @"--",
    @"*",
    @"*=",
    @"/",
    @"/=",
    @"%",
    @"%=",
    @"^",
    @"^=",
    @"<",
    @"<=",
    @"<<",
    @"<<=",
    @">",
    @">=",
    @">>",
    @">>=",
    @"_",
    // For errors
    @"\n",

    k_alias,
    k_break,
    k_case,
    k_const,
    k_const_assert,
    k_continue,
    k_continuing,
    k_default,
    k_diagnostic,
    k_discard,
    k_else,
    k_enable,
    k_false,
    k_fn,
    k_for,
    k_if,
    k_let,
    k_loop,
    k_override,
    k_requires,
    k_return,
    k_struct,
    k_switch,
    k_true,
    k_var,
    k_while,
    // Not part of spec.
    k_import,
    k_as,
    k_from,

    const Self = @This();

    pub fn symbol(self: Self) []const u8 {
        return switch (self) {
            .eof => "EOF",
            .invalid => "invalid bytes",
            .ident => "an identifier",
            .number => "a number literal",
            .string_literal => "a string literal",
            .template_args_start => "<",
            .template_args_end => ">",

            .@"(",
            .@")",
            .@"{",
            .@"}",
            .@"[",
            .@"]",
            .@".",
            .@",",
            .@":",
            .@";",
            .@"->",
            .@"@",
            .@"=",
            .@"==",
            .@"!",
            .@"!=",
            .@"&",
            .@"&=",
            .@"&&",
            .@"|",
            .@"|=",
            .@"||",
            .@"~",
            .@"+",
            .@"+=",
            .@"++",
            .@"-",
            .@"-=",
            .@"--",
            .@"*",
            .@"*=",
            .@"/",
            .@"/=",
            .@"%",
            .@"%=",
            .@"^",
            .@"^=",
            .@"<",
            .@"<=",
            .@"<<",
            .@"<<=",
            .@">",
            .@">=",
            .@">>",
            .@">>=",
            ._,
            => |t| @tagName(t),

            .k_import => "// import",
            else => |t| @tagName(t)["k_".len..],
        };
    }
};

pub const keywords = brk: {
    @setEvalBranchQuota(3000);
    const KV = struct { []const u8, Tag };
    var kvs: [100]KV = undefined;
    var i: usize = 0;
    for (@typeInfo(Tag).Enum.fields) |f| {
        if (f.name.len >= 2 and std.mem.eql(u8, f.name[0..2], "k_")) {
            kvs[i] = KV{ f.name[2..], @enumFromInt(f.value) };
            i += 1;
        }
    }
    break :brk std.ComptimeStringMap(Tag, kvs[0..i]);
};

pub const reserved = blk: {
    @setEvalBranchQuota(3000);
    break :blk std.ComptimeStringMap(void, .{
        .{"NULL"},
        .{"Self"},
        .{"abstract"},
        .{"active"},
        .{"alignas"},
        .{"alignof"},
        .{"as"},
        .{"asm"},
        .{"asm_fragment"},
        .{"async"},
        .{"attribute"},
        .{"auto"},
        .{"await"},
        .{"become"},
        .{"binding_array"},
        .{"cast"},
        .{"catch"},
        .{"class"},
        .{"co_await"},
        .{"co_return"},
        .{"co_yield"},
        .{"coherent"},
        .{"column_major"},
        .{"common"},
        .{"compile"},
        .{"compile_fragment"},
        .{"concept"},
        .{"const_cast"},
        .{"consteval"},
        .{"constexpr"},
        .{"constinit"},
        .{"crate"},
        .{"debugger"},
        .{"decltype"},
        .{"delete"},
        .{"demote"},
        .{"demote_to_helper"},
        .{"do"},
        .{"dynamic_cast"},
        .{"enum"},
        .{"explicit"},
        .{"export"},
        .{"extends"},
        .{"extern"},
        .{"external"},
        .{"fallthrough"},
        .{"filter"},
        .{"final"},
        .{"finally"},
        .{"friend"},
        .{"from"},
        .{"fxgroup"},
        .{"get"},
        .{"goto"},
        .{"groupshared"},
        .{"highp"},
        .{"impl"},
        .{"implements"},
        .{"import"},
        .{"inline"},
        .{"instanceof"},
        .{"interface"},
        .{"layout"},
        .{"lowp"},
        .{"macro"},
        .{"macro_rules"},
        .{"match"},
        .{"mediump"},
        .{"meta"},
        .{"mod"},
        .{"module"},
        .{"move"},
        .{"mut"},
        .{"mutable"},
        .{"namespace"},
        .{"new"},
        .{"nil"},
        .{"noexcept"},
        .{"noinline"},
        .{"nointerpolation"},
        .{"noperspective"},
        .{"null"},
        .{"nullptr"},
        .{"of"},
        .{"operator"},
        .{"package"},
        .{"packoffset"},
        .{"partition"},
        .{"pass"},
        .{"patch"},
        .{"pixelfragment"},
        .{"precise"},
        .{"precision"},
        .{"premerge"},
        .{"priv"},
        .{"protected"},
        .{"pub"},
        .{"public"},
        .{"readonly"},
        .{"ref"},
        .{"regardless"},
        .{"register"},
        .{"reinterpret_cast"},
        .{"require"},
        .{"resource"},
        .{"restrict"},
        .{"self"},
        .{"set"},
        .{"shared"},
        .{"sizeof"},
        .{"smooth"},
        .{"snorm"},
        .{"static"},
        .{"static_assert"},
        .{"static_cast"},
        .{"std"},
        .{"subroutine"},
        .{"super"},
        .{"target"},
        .{"template"},
        .{"this"},
        .{"thread_local"},
        .{"throw"},
        .{"trait"},
        .{"try"},
        .{"type"},
        .{"typedef"},
        .{"typeid"},
        .{"typename"},
        .{"typeof"},
        .{"union"},
        .{"unless"},
        .{"unorm"},
        .{"unsafe"},
        .{"unsized"},
        .{"use"},
        .{"using"},
        .{"varying"},
        .{"virtual"},
        .{"volatile"},
        .{"wgsl"},
        .{"where"},
        .{"with"},
        .{"writeonly"},
        .{"yield"},
    });
};
